const fs = require('fs');
const path = require('path');
const sharp = require('sharp');
const { minify } = require('html-minifier-terser');

const DIST_DIR = path.join(__dirname, 'dist');
const SOURCE_HTML = path.join(__dirname, 'index.html');
const SOURCE_IMAGES = [
  'Logo_GastroUp_2_transparent.png',
  'Zakladatel_Jakub_Hnat.png'
];
const COPY_FILES = [
  'og-image.png',
  'favicon.ico',
  'favicon-192.png',
  'favicon-512.png',
  'apple-touch-icon.png',
  'robots.txt',
  'sitemap.xml',
  'llms.txt',
  'site.webmanifest',
  '404.html'
];
const EXCLUDE_DIRS = [
  'napady-fotografie.html',
  'Logo-Design',
  'Assets',
  'brand-assets',
  'Kampaně',
  'Website-Copy',
  'node_modules',
  'docs'
];

const minifyOptions = {
  collapseWhitespace: true,
  removeComments: true,
  minifyJS: true,
  minifyCSS: true,
  removeRedundantAttributes: true,
  keepClosingSlash: false
};

(async () => {
  try {
    // Clean and recreate dist directory
    if (fs.existsSync(DIST_DIR)) {
      fs.rmSync(DIST_DIR, { recursive: true, force: true });
    }
    fs.mkdirSync(DIST_DIR, { recursive: true });

    console.log('🔨 Starting build process...\n');

    // ============ Step 1: Minify HTML ============
    if (!fs.existsSync(SOURCE_HTML)) {
      console.error(`ERROR: index.html not found at ${SOURCE_HTML}`);
      process.exit(1);
    }

    const originalHTML = fs.readFileSync(SOURCE_HTML, 'utf8');
    const originalSize = Buffer.byteLength(originalHTML, 'utf8');

    console.log(`📄 Minifying index.html (${originalSize} bytes)...`);
    const minifiedHTML = await minify(originalHTML, minifyOptions);
    const minifiedSize = Buffer.byteLength(minifiedHTML, 'utf8');

    fs.writeFileSync(path.join(DIST_DIR, 'index.html'), minifiedHTML, 'utf8');
    console.log(`   ✓ Minified: ${minifiedSize} bytes (saved ${originalSize - minifiedSize} bytes, ${Math.round((1 - minifiedSize / originalSize) * 100)}%)\n`);

    // ============ Step 2: Process images with sharp ============
    for (const imageName of SOURCE_IMAGES) {
      const imagePath = path.join(__dirname, imageName);
      if (!fs.existsSync(imagePath)) {
        console.error(`ERROR: Required image not found: ${imageName}`);
        process.exit(1);
      }

      const baseName = path.parse(imageName).name;
      console.log(`🖼️  Processing ${imageName}...`);

      // Copy original PNG
      const destPng = path.join(DIST_DIR, imageName);
      fs.copyFileSync(imagePath, destPng);
      const pngSize = fs.statSync(destPng).size;
      console.log(`   ✓ Copied original PNG: ${pngSize} bytes`);

      // Generate WebP
      const destWebp = path.join(DIST_DIR, `${baseName}.webp`);
      await sharp(imagePath).webp({ quality: 82 }).toFile(destWebp);
      const webpSize = fs.statSync(destWebp).size;
      console.log(`   ✓ Generated WebP: ${webpSize} bytes (saved ${pngSize - webpSize} bytes)`);

      // Generate AVIF
      const destAvif = path.join(DIST_DIR, `${baseName}.avif`);
      await sharp(imagePath).avif({ quality: 55 }).toFile(destAvif);
      const avifSize = fs.statSync(destAvif).size;
      console.log(`   ✓ Generated AVIF: ${avifSize} bytes (saved ${pngSize - avifSize} bytes)\n`);
    }

    // ============ Step 3: Copy curated files ============
    console.log('📋 Copying curated files...');
    const missingFiles = [];

    for (const file of COPY_FILES) {
      const srcPath = path.join(__dirname, file);
      if (fs.existsSync(srcPath)) {
        const destPath = path.join(DIST_DIR, file);
        fs.copyFileSync(srcPath, destPath);
        const fileSize = fs.statSync(destPath).size;
        console.log(`   ✓ ${file} (${fileSize} bytes)`);
      } else {
        missingFiles.push(file);
      }
    }

    if (missingFiles.length > 0) {
      console.log(`\n⚠️  WARNING: The following files were not found in source (may be generated by parallel tasks):`);
      missingFiles.forEach(f => console.log(`   - ${f}`));
    }

    // Copy fonts directory if it exists
    const fontsDir = path.join(__dirname, 'fonts');
    if (fs.existsSync(fontsDir)) {
      const destFontsDir = path.join(DIST_DIR, 'fonts');
      fs.mkdirSync(destFontsDir, { recursive: true });
      const fontsFiles = fs.readdirSync(fontsDir);
      for (const file of fontsFiles) {
        const srcFile = path.join(fontsDir, file);
        const destFile = path.join(destFontsDir, file);
        if (fs.statSync(srcFile).isFile()) {
          fs.copyFileSync(srcFile, destFile);
          console.log(`   ✓ fonts/${file}`);
        }
      }
    }

    console.log('\n✅ Build complete!\n');

    // ============ Summary ============
    const distFiles = getAllFiles(DIST_DIR);
    const distSize = distFiles.reduce((sum, file) => sum + fs.statSync(file).size, 0);
    console.log('📊 Build Summary:');
    console.log(`   Files written: ${distFiles.length}`);
    console.log(`   Total dist size: ${distSize} bytes (${(distSize / 1024).toFixed(2)} KB)`);
    console.log(`   HTML minification: ${Math.round((1 - minifiedSize / originalSize) * 100)}% reduction`);

  } catch (error) {
    console.error('❌ Build failed:', error.message);
    process.exit(1);
  }
})();

function getAllFiles(dirPath, arrayOfFiles = []) {
  const files = fs.readdirSync(dirPath);
  files.forEach(file => {
    const filePath = path.join(dirPath, file);
    if (fs.statSync(filePath).isDirectory()) {
      arrayOfFiles = getAllFiles(filePath, arrayOfFiles);
    } else {
      arrayOfFiles.push(filePath);
    }
  });
  return arrayOfFiles;
}
